### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by matstc** [mmckegg/bopper#6]
Hello—I'd like to use bopper in my app but I'm unsure what the licensing terms are for this project.

From the [npm package page](https://www.npmjs.com/package/bopper), it looks like the package is licensed under an MIT license. Is that correct? And who should we quote as the owner of the copyright?

Thanks!

**Comment by mmckegg** [comment]
Yes it is MIT, and I (Matt McKegg) am the owner of the copyright as per the author field in the package.json file.

**Comment by matstc** [comment]
Great. Thanks, Matt. I'm also using ditty and I'll be quoting the same license and owner.

Thanks a lot.
